// Figure data for dynamic generation
const figureData = [
  // Roman Figures
  { category: "ROMAN", name: "Jupiter", image: "jupiter.webp" },
  { category: "ROMAN", name: "Venus", image: "venus.webp" },
  { category: "ROMAN", name: "Mars", image: "mars.webp" },
  { category: "ROMAN", name: "Minerva", image: "minerva.webp" },
  { category: "ROMAN", name: "Diana", image: "diana.webp" },
  { category: "ROMAN", name: "Apollo", image: "apollo-roman.webp" },
  { category: "ROMAN", name: "Janus", image: "janus.webp" },
  { category: "ROMAN", name: "Rom and Rem", image: "romulus-remus.webp" },
  { category: "ROMAN", name: "Neptune", image: "neptune.webp" },
  { category: "ROMAN", name: "Vulcan", image: "vulcan.webp" },

  // Greek Figures
  { category: "GREEK", name: "Zeus", image: "zeus.webp" },
  { category: "GREEK", name: "Athena", image: "athena.webp" },
  { category: "GREEK", name: "Poseidon", image: "poseidon.webp" },
  { category: "GREEK", name: "Aphrodite", image: "aphrodite.webp" },
  { category: "GREEK", name: "Ares", image: "ares.webp" },
  { category: "GREEK", name: "Artemis", image: "artemis.webp" },
  { category: "GREEK", name: "Apollo", image: "apollo-greek.webp" },
  { category: "GREEK", name: "Hermes", image: "hermes.webp" },
  { category: "GREEK", name: "Hera", image: "hera.webp" },
  { category: "GREEK", name: "Hades", image: "hades.webp" },

  // Norse Figures
  { category: "NORSE", name: "Odin", image: "odin.webp" },
  { category: "NORSE", name: "Thor", image: "thor.webp" },
  { category: "NORSE", name: "Loki", image: "loki.webp" },
  { category: "NORSE", name: "Freya", image: "freya.webp" },
  { category: "NORSE", name: "Baldur", image: "baldur.webp" },
  { category: "NORSE", name: "Frigg", image: "frigg.webp" },
  { category: "NORSE", name: "Tyr", image: "tyr.webp" },
  { category: "NORSE", name: "Heimdall", image: "heimdall.webp" },
  { category: "NORSE", name: "Hel", image: "hel.webp" },
  { category: "NORSE", name: "Njord", image: "njord.webp" },

  // Egyptian Figures
  { category: "EGYPTIAN", name: "Ra", image: "ra.webp" },
  { category: "EGYPTIAN", name: "Isis", image: "isis.webp" },
  { category: "EGYPTIAN", name: "Anubis", image: "anubis.webp" },
  { category: "EGYPTIAN", name: "Horus", image: "horus.webp" },
  { category: "EGYPTIAN", name: "Cleopatra", image: "cleopatra.webp" },
  { category: "EGYPTIAN", name: "Osiris", image: "osiris.webp" },
  { category: "EGYPTIAN", name: "Thoth", image: "thoth.webp" },
  { category: "EGYPTIAN", name: "Hathor", image: "hathor.webp" },
  { category: "EGYPTIAN", name: "Sekhmet", image: "sekhmet.webp" },
  { category: "EGYPTIAN", name: "Bastet", image: "bastet.webp" },

  // Japanese Figures
  { category: "JAPANESE", name: "Amaterasu", image: "amaterasu.webp" },
  { category: "JAPANESE", name: "Susanoo", image: "susanoo.webp" },
  { category: "JAPANESE", name: "Tsukuyomi", image: "tsukuyomi.webp" },
  { category: "JAPANESE", name: "Inari", image: "inari.webp" },
  { category: "JAPANESE", name: "Raijin", image: "raijin.webp" },
  { category: "JAPANESE", name: "Fujin", image: "fujin.webp" },
  { category: "JAPANESE", name: "Hachiman", image: "hachiman.webp" },
  { category: "JAPANESE", name: "Kannon", image: "kannon.webp" },
  { category: "JAPANESE", name: "Jizo", image: "jizo.webp" },
  { category: "JAPANESE", name: "Tenjin", image: "tenjin.webp" },

  // Celtic Figures
  { category: "CELTIC", name: "Cernunnos", image: "cernunnos.webp" },
  { category: "CELTIC", name: "Morrigan", image: "morrigan.webp" },
  { category: "CELTIC", name: "Brigid", image: "brigid.webp" },
  { category: "CELTIC", name: "Lugh", image: "lugh.webp" },
  { category: "CELTIC", name: "Manannán", image: "manannan.webp" },
  { category: "CELTIC", name: "Danu", image: "danu.webp" },
  { category: "CELTIC", name: "Aengus", image: "aengus.webp" },
  { category: "CELTIC", name: "Dagda", image: "dagda.webp" },
  { category: "CELTIC", name: "Epona", image: "epona.webp" },
  { category: "CELTIC", name: "Bran the Blessed", image: "bran.webp" },

  // Aztec Figures
  { category: "AZTEC", name: "Quetzalcoatl", image: "quetzalcoatl.webp" },
  { category: "AZTEC", name: "Tezcatlipoca", image: "tezcatlipoca.webp" },
  { category: "AZTEC", name: "Huitzilopochtli", image: "huitzilopochtli.webp" },
  { category: "AZTEC", name: "Tlaloc", image: "tlaloc.webp" },
  { category: "AZTEC", name: "Xochiquetzal", image: "xochiquetzal.webp" },
  { category: "AZTEC", name: "Mictlantecuhtli", image: "mictlantecuhtli.webp" },
  { category: "AZTEC", name: "Chalchiuhtlicue", image: "chalchiuhtlicue.webp" },
  { category: "AZTEC", name: "Coyolxauhqui", image: "coyolxauhqui.webp" },
  { category: "AZTEC", name: "Mixcoatl", image: "mixcoatl.webp" },
  { category: "AZTEC", name: "Tlazolteotl", image: "tlazolteotl.webp" },
];

// Detailed deity data for dynamic page generation
const deityData = {
  // Greek Deities
  Zeus: {
    name: "Zeus",
    greekName: "Ζεύς",
    category: "GREEK",
    image: "zeus.webp",
    origins: "Son of Cronus and Rhea; king of the Olympian gods after defeating the Titans.",
    symbols: "Thunderbolt, eagle, oak tree, scepter.",
    curiosities: "Known for many love affairs and children (e.g., Heracles, Athena).",
    quote: "Zeus who thunders on high rules over all the immortals.",
    quoteSource: "Hesiod, Theogony, line 73",
    description:
      'Zeus is the king of the gods in ancient Greek mythology and ruler of the sky and thunder. He is the youngest son of the Titans Cronus and Rhea. When Cronus learned that one of his children would overthrow him, he swallowed each one at birth. But Rhea saved the youngest—Zeus—by hiding him in a cave on the island of Crete and giving Cronus a stone wrapped in cloth instead. Once grown, Zeus returned, forced Cronus to vomit up his siblings (Hestia, Demeter, Hera, Hades, and Poseidon), and led them in a war against the Titans, known as the Titanomachy. After their victory, Zeus became the ruler of the heavens, Poseidon took the sea, and Hades ruled the underworld. Zeus maintained order among gods and mortals and was often called "Father of gods and men." He had many relationships with both goddesses and mortal women, fathering many important figures like Athena, Apollo, Artemis, Hermes, Heracles, and Perseus. He was worshipped throughout ancient Greece, especially in Olympia, where the Olympic Games were held in his honor.',
  },
  Athena: {
    name: "Athena",
    greekName: "Ἀθηνᾶ",
    category: "GREEK",
    image: "athena.webp",
    origins: "Born from Zeus's head fully grown and armored, goddess of wisdom and warfare.",
    symbols: "Owl, olive tree, shield (aegis), spear.",
    curiosities: "Patron goddess of Athens; invented the flute but cursed it when she saw her reflection.",
    quote: "Wisdom begins in wonder.",
    quoteSource: "Often attributed to Athena's teachings",
    description:
      "Athena is the Greek goddess of wisdom, warfare, and crafts. Born from Zeus's head fully grown and armed, she represents strategic warfare rather than brutal combat. As patron of Athens, she gifted the olive tree to the city. Known for her intelligence and tactical skills, she aided many heroes including Odysseus and Perseus. Her sacred animal is the owl, symbolizing wisdom.",
  },
  Poseidon: {
    name: "Poseidon",
    greekName: "Ποσειδῶν",
    category: "GREEK",
    image: "poseidon.webp",
    origins: "Son of Cronus and Rhea, brother of Zeus; ruler of the seas and earthquakes.",
    symbols: "Trident, horse, dolphin, bull.",
    curiosities: "Created the first horse; lost the contest for Athens to Athena by offering a salt spring.",
    quote: "The earth-shaker stirs the boundless sea.",
    quoteSource: "Homer, Iliad",
    description:
      "Poseidon is the Greek god of the sea, earthquakes, and horses. One of the twelve Olympians and brother to Zeus and Hades, he rules over all bodies of water. Known for his volatile temper, he could cause earthquakes and tsunamis when angered. His weapon is the trident, which he uses to create springs, cause earthquakes, and stir up the seas.",
  },
  Aphrodite: {
    name: "Aphrodite",
    greekName: "Ἀφροδίτη",
    category: "GREEK",
    image: "aphrodite.webp",
    origins: "Born from sea foam near Cyprus; goddess of love, beauty, and pleasure.",
    symbols: "Dove, rose, shell, myrtle, swan.",
    curiosities: "Married to Hephaestus but had affairs with Ares; caused the Trojan War through Paris's judgment.",
    quote: "Love conquers all things; let us too surrender to love.",
    quoteSource: "Virgil, inspired by Aphrodite",
    description:
      "Aphrodite is the Greek goddess of love, beauty, pleasure, and procreation. Born from sea foam, she represents both sacred and profane love. Though married to Hephaestus, she had many affairs, most notably with Ares. Her beauty and power over love made her one of the most influential deities in Greek mythology.",
  },
  Ares: {
    name: "Ares",
    greekName: "Ἄρης",
    category: "GREEK",
    image: "ares.webp",
    origins: "Son of Zeus and Hera; god of war, courage, and civil order.",
    symbols: "Spear, shield, helmet, boar, vulture.",
    curiosities: "Often portrayed as cowardly despite being god of war; had affair with Aphrodite.",
    quote: "In war, truth is the first casualty.",
    quoteSource: "Ancient Greek wisdom associated with Ares",
    description:
      "Ares is the Greek god of war, representing the brutal and violent aspects of battle. Unlike Athena's strategic warfare, Ares embodies raw aggression and bloodlust. Son of Zeus and Hera, he was not popular among the Greeks, who saw him as representing the negative aspects of conflict.",
  },
  Artemis: {
    name: "Artemis",
    greekName: "Ἄρτεμις",
    category: "GREEK",
    image: "artemis.webp",
    origins: "Daughter of Zeus and Leto, twin sister of Apollo; goddess of the hunt and moon.",
    symbols: "Silver bow, deer, cypress tree, amaranth flower.",
    curiosities: "Eternal virgin who punished those who tried to court her; protector of young animals.",
    quote: "I shall remain a virgin always, and I shall hunt with my nymphs.",
    quoteSource: "Homeric Hymns",
    description:
      "Artemis is the Greek goddess of the hunt, wilderness, and childbirth. Twin sister to Apollo, she chose eternal virginity and leads a group of hunting nymphs. Known for her fierce protection of her chastity and her hunting prowess, she could be both protector and destroyer.",
  },
  Apollo: {
    name: "Apollo",
    greekName: "Ἀπόλλων",
    category: "GREEK",
    image: "apollo-greek.webp",
    origins: "Son of Zeus and Leto, twin brother of Artemis; god of music, poetry, and the sun.",
    symbols: "Lyre, laurel wreath, bow and arrow, raven, sun.",
    curiosities: "Oracle at Delphi spoke his prophecies; patron of the nine Muses.",
    quote: "Know thyself.",
    quoteSource: "Inscribed at Apollo's temple at Delphi",
    description:
      "Apollo is one of the most important Olympian deities, god of music, poetry, art, oracles, archery, plague, medicine, sun, light, and knowledge. Twin brother to Artemis, he represents harmony, order, and reason. The Oracle at Delphi was his most famous shrine.",
  },
  Hermes: {
    name: "Hermes",
    greekName: "Ἑρμῆς",
    category: "GREEK",
    image: "hermes.webp",
    origins: "Son of Zeus and the nymph Maia; messenger of the gods and guide to the underworld.",
    symbols: "Caduceus, winged sandals, traveler's hat, tortoise.",
    curiosities: "Invented the lyre as a baby and traded it to Apollo; guide for souls to the afterlife.",
    quote: "The way up and down are one and the same.",
    quoteSource: "Heraclitus, reflecting Hermes' role as psychopomp",
    description:
      "Hermes is the messenger of the gods, god of trade, thieves, travel, and guide to the underworld. Known for his cunning and speed, he serves as herald to Zeus and psychopomp, leading souls to the afterlife. He invented the lyre and is patron of merchants and travelers.",
  },
  Hera: {
    name: "Hera",
    greekName: "Ἥρα",
    category: "GREEK",
    image: "hera.webp",
    origins: "Daughter of Cronus and Rhea, wife and sister of Zeus; queen of the gods.",
    symbols: "Peacock, cow, pomegranate, crown.",
    curiosities: "Jealous wife who pursued Zeus's lovers and children; protector of marriage.",
    quote: "Marriage is the union of two people who agree to live together.",
    quoteSource: "Ancient Greek wedding traditions honoring Hera",
    description:
      "Hera is the queen of the gods, goddess of marriage, women, childbirth, and family. Wife and sister of Zeus, she is known for her jealous nature regarding Zeus's many affairs. Despite this, she remains the protector of marriage and women in childbirth.",
  },
  Hades: {
    name: "Hades",
    greekName: "ᾍδης",
    category: "GREEK",
    image: "hades.webp",
    origins: "Son of Cronus and Rhea, brother of Zeus and Poseidon; ruler of the underworld.",
    symbols: "Cerberus, cypress tree, narcissus flower, key, scepter.",
    curiosities: "Kidnapped Persephone to be his queen; rarely left the underworld.",
    quote: "Death is not the greatest loss in life. The greatest loss is what dies inside while still alive.",
    quoteSource: "Greek philosophical thought on death",
    description:
      "Hades is the Greek god of the dead and ruler of the underworld. Brother to Zeus and Poseidon, he governs the realm of the dead with his wife Persephone. Though feared, he is not evil but rather stern and unyielding in his duties as judge of the dead.",
  },

  // Roman Deities
  Jupiter: {
    name: "Jupiter",
    romanName: "Iuppiter",
    category: "ROMAN",
    image: "jupiter.webp",
    origins: "King of the Roman gods, equivalent to Greek Zeus; ruler of the sky and thunder.",
    symbols: "Eagle, thunderbolt, oak tree, scepter.",
    curiosities: "Romans built many temples in his honor; father of the gods in Roman pantheon.",
    quote: "Jupiter Optimus Maximus guides the fate of Rome.",
    quoteSource: "Roman religious inscriptions",
    description:
      "Jupiter is the king of the Roman gods, equivalent to the Greek Zeus. As ruler of the sky and thunder, he was the most important deity in the Roman pantheon. Romans believed he protected the state and its people, and many temples were built in his honor throughout the empire.",
  },
  Venus: {
    name: "Venus",
    romanName: "Venus",
    category: "ROMAN",
    image: "venus.webp",
    origins: "Roman goddess of love, beauty, and fertility; identified with Greek Aphrodite.",
    symbols: "Rose, dove, shell, myrtle, swan.",
    curiosities: "Mother of Aeneas, founder of Roman lineage; patron of gardens and vineyards.",
    quote: "Love conquers all; yield to love.",
    quoteSource: "Virgil, Eclogues",
    description: "Venus is the Roman goddess of love, beauty, desire, and fertility. As mother of Aeneas, she played a crucial role in Roman foundation myths. More dignified than her Greek counterpart Aphrodite, Venus embodied the Roman ideals of marriage and family."
  },
  Mars: {
    name: "Mars",
    romanName: "Mars",
    category: "ROMAN",
    image: "mars.webp",
    origins: "Roman god of war and agriculture; father of Romulus and Remus.",
    symbols: "Spear, shield, wolf, woodpecker.",
    curiosities: "Unlike Greek Ares, Mars was highly respected as protector of Rome.",
    quote: "Rome was not built in a day, but Mars watches over it always.",
    quoteSource: "Roman military traditions",
    description: "Mars is the Roman god of war and guardian of agriculture. As father of Romulus and Remus, he holds special significance as protector of Rome. Unlike the Greeks' view of Ares, Romans revered Mars as a dignified defender of the state."
  },
  Minerva: {
    name: "Minerva",
    romanName: "Minerva",
    category: "ROMAN",
    image: "minerva.webp",
    origins: "Roman goddess of wisdom, warfare, and crafts; equivalent to Greek Athena.",
    symbols: "Owl, olive tree, shield, spear.",
    curiosities: "Part of the Capitoline Triad with Jupiter and Juno; patron of artisans.",
    quote: "Wisdom is the highest virtue.",
    quoteSource: "Roman philosophical traditions",
    description: "Minerva is the Roman goddess of wisdom, strategic warfare, and handicrafts. Member of the Capitoline Triad, she protected Rome alongside Jupiter and Juno. She guided craftsmen, teachers, and artists in their endeavors."
  },
  Diana: {
    name: "Diana",
    romanName: "Diana",
    category: "ROMAN",
    image: "diana.webp",
    origins: "Roman goddess of the hunt, moon, and childbirth; equivalent to Greek Artemis.",
    symbols: "Silver bow, deer, moon, cypress tree.",
    curiosities: "Protector of women in childbirth despite being eternally virgin.",
    quote: "I am the huntress of the silver moon.",
    quoteSource: "Roman hymns to Diana",
    description: "Diana is the Roman goddess of the hunt, wild animals, and the moon. Like her Greek counterpart Artemis, she remained eternally virgin but protected women in childbirth. Her temple at Ephesus was one of the Seven Wonders."
  },
  Janus: {
    name: "Janus",
    romanName: "Janus",
    category: "ROMAN",
    image: "janus.webp",
    origins: "Uniquely Roman god of beginnings, transitions, and doorways.",
    symbols: "Two faces, keys, doors, gates.",
    curiosities: "Month of January named after him; consulted before all other gods.",
    quote: "I see the past and future, for I am the guardian of transitions.",
    quoteSource: "Roman prayers to Janus",
    description: "Janus is the uniquely Roman god of beginnings, transitions, and doorways. Depicted with two faces looking opposite directions, he sees past and future. As guardian of boundaries and time, he was invoked at the start of any endeavor."
  },
  Neptune: {
    name: "Neptune",
    romanName: "Neptune",
    category: "ROMAN",
    image: "neptune.webp",
    origins: "Roman god of the sea and horses; equivalent to Greek Poseidon.",
    symbols: "Trident, horse, dolphin, bull.",
    curiosities: "More peaceful than Poseidon; patron of horse racing.",
    quote: "I rule the vast expanse of the wine-dark sea.",
    quoteSource: "Roman naval prayers",
    description: "Neptune is the Roman god of the sea, earthquakes, and horses. More benevolent than his Greek counterpart Poseidon, he protected Roman naval expeditions and was patron of horse racing. His festival, Neptunalia, was celebrated in July."
  },
  Vulcan: {
    name: "Vulcan",
    romanName: "Vulcan",
    category: "ROMAN",
    image: "vulcan.webp",
    origins: "Roman god of fire, metalworking, and the forge; equivalent to Greek Hephaestus.",
    symbols: "Hammer, anvil, tongs, volcano.",
    curiosities: "His forge was said to be beneath Mount Vesuvius.",
    quote: "From fire comes creation, from the forge comes civilization.",
    quoteSource: "Roman blacksmith prayers",
    description: "Vulcan is the Roman god of fire, volcanoes, and metalworking. His forge beneath Mount Vesuvius produced weapons for gods and heroes. Patron of blacksmiths and craftsmen, he embodied the transformative power of fire."
  },

  // Norse Deities
  Odin: {
    name: "Odin",
    norseName: "Óðinn",
    category: "NORSE",
    image: "odin.webp",
    origins: "All-Father of the Norse gods; ruler of Asgard and seeker of wisdom.",
    symbols: "Two ravens (Huginn and Muninn), eight-legged horse Sleipnir, spear Gungnir.",
    curiosities: "Sacrificed his eye for wisdom; hung himself from Yggdrasil for nine days to learn runes.",
    quote: "Wisdom is welcome wherever it comes from.",
    quoteSource: "Havamal (Sayings of the High One)",
    description:
      "Odin is the All-Father and chief of the Norse gods, ruler of Asgard and god of wisdom, war, and death. Known for his relentless pursuit of knowledge, he sacrificed his eye for wisdom and discovered the runes. He leads the Wild Hunt and gathers fallen warriors in Valhalla.",
  },
  Thor: {
    name: "Thor",
    norseName: "Þórr",
    category: "NORSE",
    image: "thor.webp",
    origins: "Son of Odin; god of thunder, strength, and protection of mankind.",
    symbols: "Hammer Mjolnir, belt of strength, iron gloves, goats.",
    curiosities: "Most popular Norse god among common people; destined to die killing Jormungandr at Ragnarök.",
    quote: "I would rather be a hammer than a nail.",
    quoteSource: "Norse warrior tradition",
    description:
      "Thor is the Norse god of thunder, lightning, oak trees, strength, and the protection of mankind. Son of Odin, he wields the mighty hammer Mjolnir and rides in a chariot pulled by two goats. He is destined to fight the World Serpent Jormungandr at Ragnarök.",
  },
  Loki: {
    name: "Loki",
    norseName: "Loki",
    category: "NORSE",
    image: "loki.webp",
    origins: "Blood brother of Odin; trickster god and shape-shifter.",
    symbols: "Fire, serpent, falcon, horse, fishing net.",
    curiosities: "Father of monsters including Fenrir and Jormungandr; bound until Ragnarök as punishment.",
    quote: "I am burdened with glorious purpose.",
    quoteSource: "Modern interpretation of Loki's character",
    description:
      "Loki is the Norse trickster god, blood brother to Odin and shape-shifter extraordinaire. Neither fully god nor giant, he walks between worlds, often helping and hindering the gods. His actions will ultimately lead to Ragnarök, the end of the world.",
  },
  Freya: {
    name: "Freya",
    norseName: "Freyja",
    category: "NORSE",
    image: "freya.webp",
    origins: "Norse goddess of love, fertility, war, and death; leader of the Vanir.",
    symbols: "Falcon cloak, amber necklace Brísingamen, boar, cat.",
    curiosities: "Claims half of the battle-slain for her hall Sessrúmnir.",
    quote: "Love and war are two sides of the same blade.",
    quoteSource: "Poetic Edda",
    description: "Freya is the Norse goddess of love, beauty, fertility, war, and death. A member of the Vanir, she possesses the falcon cloak that allows flight and the precious necklace Brísingamen. She shares the battle-slain with Odin."
  },
  Baldur: {
    name: "Baldur",
    norseName: "Baldr",
    category: "NORSE",
    image: "baldur.webp",
    origins: "Norse god of light, purity, and summer; son of Odin and Frigg.",
    symbols: "Light, ship Hringhorni, mistletoe.",
    curiosities: "His death signals the beginning of Ragnarök.",
    quote: "Even the gods cannot escape the bonds of fate.",
    quoteSource: "Prose Edda",
    description: "Baldur is the Norse god of light, purity, beauty, and summer. Son of Odin and Frigg, he was beloved by all except Loki. His death by mistletoe, orchestrated by Loki, marks the beginning of the events leading to Ragnarök."
  },
  Frigg: {
    name: "Frigg",
    norseName: "Frigg",
    category: "NORSE",
    image: "frigg.webp",
    origins: "Norse goddess of marriage, motherhood, and domestic life; wife of Odin.",
    symbols: "Spinning wheel, keys, falcon feathers.",
    curiosities: "Knows the fate of all beings but never speaks of it.",
    quote: "A mother's love reaches beyond the boundaries of the nine realms.",
    quoteSource: "Norse maternal wisdom",
    description: "Frigg is the Norse goddess of marriage, motherhood, and the household. Wife of Odin and mother of Baldur, she possesses the gift of prophecy but keeps her knowledge secret. She represents the protective power of maternal love."
  },
  Tyr: {
    name: "Tyr",
    norseName: "Týr",
    category: "NORSE",
    image: "tyr.webp",
    origins: "Norse god of war, justice, and sacrifice; lost his hand to Fenrir.",
    symbols: "One hand, sword, scales of justice.",
    curiosities: "Only god brave enough to feed Fenrir; lost hand binding the wolf.",
    quote: "Honor demands sacrifice, even of oneself.",
    quoteSource: "Germanic warrior traditions",
    description: "Tyr is the Norse god of war, justice, and honor. He sacrificed his hand to bind the wolf Fenrir, demonstrating the principle that justice sometimes requires personal sacrifice. He represents courage and the rule of law."
  },
  Heimdall: {
    name: "Heimdall",
    norseName: "Heimdallr",
    category: "NORSE",
    image: "heimdall.webp",
    origins: "Norse guardian god of Bifrost bridge; watchman of the gods.",
    symbols: "Horn Gjallarhorn, rainbow bridge, keen sight and hearing.",
    curiosities: "Can see for hundreds of miles and hear grass growing.",
    quote: "I stand eternal watch over the rainbow bridge.",
    quoteSource: "Poetic Edda",
    description: "Heimdall is the Norse guardian god who watches over Bifrost, the rainbow bridge connecting Asgard and Midgard. Possessing extraordinary sight and hearing, he will blow the horn Gjallarhorn to signal the onset of Ragnarök."
  },
  Hel: {
    name: "Hel",
    norseName: "Hel",
    category: "NORSE",
    image: "hel.webp",
    origins: "Norse goddess of death and the underworld; daughter of Loki.",
    symbols: "Half-living/half-corpse appearance, realm of the dead.",
    curiosities: "Rules over those who die of sickness or old age.",
    quote: "In my realm, all are equal - king and commoner alike.",
    quoteSource: "Norse death traditions",
    description: "Hel is the Norse goddess of death and ruler of the underworld realm that bears her name. Daughter of Loki, she appears half-alive and half-corpse. She governs the souls of those who die of illness or old age."
  },
  Njord: {
    name: "Njord",
    norseName: "Njörðr",
    category: "NORSE",
    image: "njord.webp",
    origins: "Norse god of the sea, wind, and fishing; father of Freya and Freyr.",
    symbols: "Ships, seabirds, fishing nets, coastal winds.",
    curiosities: "Lives by the sea but married mountain-dwelling Skadi.",
    quote: "The sea calls to those who understand its depths.",
    quoteSource: "Norse seafaring traditions",
    description: "Njord is the Norse god of the sea, wind, fishing, and wealth. A member of the Vanir who came to Asgard as a hostage, he represents the prosperity that comes from maritime trade and fishing."
  },

  // Egyptian Deities
  Ra: {
    name: "Ra",
    egyptianName: "Rꜥ",
    category: "EGYPTIAN",
    image: "ra.webp",
    origins: "Sun god and king of the Egyptian gods; creator deity who emerged from primordial waters.",
    symbols: "Solar disk, falcon, ankh, sun barque.",
    curiosities: "Traveled through underworld each night to battle chaos serpent Apophis.",
    quote: "I am Ra, who came forth from the waters of Nun.",
    quoteSource: "Egyptian Book of the Dead",
    description:
      "Ra is the ancient Egyptian sun god and king of the gods. He traveled across the sky in his solar barque each day and through the underworld each night, battling the forces of chaos. As a creator deity, he was central to Egyptian religion and pharaonic ideology.",
  },
  Isis: {
    name: "Isis",
    egyptianName: "Aset",
    category: "EGYPTIAN",
    image: "isis.webp",
    origins: "Goddess of magic, motherhood, and healing; wife of Osiris and mother of Horus.",
    symbols: "Throne headdress, ankh, sistrum, cow horns with solar disk.",
    curiosities: "Reassembled Osiris after Set dismembered him; her worship spread throughout Roman Empire.",
    quote: "I am Isis, mistress of magic, who performs magic with words of power.",
    quoteSource: "Egyptian magical papyri",
    description:
      "Isis is one of the most important Egyptian goddesses, deity of magic, motherhood, healing, and rebirth. Wife of Osiris and mother of Horus, she used her magical powers to resurrect Osiris and protect Horus. Her cult spread throughout the ancient world.",
  },
  Anubis: {
    name: "Anubis",
    egyptianName: "Inpu",
    category: "EGYPTIAN",
    image: "anubis.webp",
    origins: "God of mummification and the afterlife; protector of graves and guide to the dead.",
    symbols: "Jackal, canopic jars, scales of justice, mummy wrappings.",
    curiosities: "Weighs hearts against the feather of Ma'at; invented mummification process.",
    quote: "I am the guardian of the sacred mysteries of death and rebirth.",
    quoteSource: "Egyptian funerary texts",
    description:
      "Anubis is the ancient Egyptian god of mummification and the afterlife. With the head of a jackal, he protects graves and guides souls through the underworld. He weighs the hearts of the dead against the feather of Ma'at to determine their fate in the afterlife.",
  },
  Horus: {
    name: "Horus",
    egyptianName: "Ḥr",
    category: "EGYPTIAN",
    image: "horus.webp",
    origins: "Son of Isis and Osiris; god of the sky, war, and protection; patron of pharaohs.",
    symbols: "Falcon, Eye of Horus, solar disk, crown of Egypt.",
    curiosities: "Lost his eye fighting Set but regained it; pharaohs considered living embodiments of Horus.",
    quote: "I am the falcon who soars above all.",
    quoteSource: "Egyptian royal inscriptions",
    description:
      "Horus is the ancient Egyptian god of the sky, war, and protection. Son of Isis and Osiris, he avenged his father's murder by defeating Set. Depicted as a falcon or falcon-headed man, Horus became the patron deity of pharaohs, who were considered his living incarnations on earth.",
  },
  Cleopatra: {
    name: "Cleopatra",
    egyptianName: "Kleopatra",
    category: "EGYPTIAN",
    image: "cleopatra.webp",
    origins: "Last pharaoh of Egypt; considered divine incarnation of Isis and Aphrodite.",
    symbols: "Serpent, ankh, crown of Egypt, lotus flower.",
    curiosities: "Spoke nine languages; allied with Julius Caesar and Mark Antony; death ended Ptolemaic dynasty.",
    quote: "I will not be triumphed over.",
    quoteSource: "Plutarch, Life of Antony",
    description:
      "Cleopatra VII was the last active pharaoh of Ptolemaic Egypt. Considered a divine incarnation of Isis, she was renowned for her intelligence, political acumen, and charisma. Her relationships with Julius Caesar and Mark Antony were both romantic and political, aimed at preserving Egypt's independence.",
  },
  Osiris: {
    name: "Osiris",
    egyptianName: "Wsir",
    category: "EGYPTIAN",
    image: "osiris.webp",
    origins: "God of the dead, underworld, and rebirth; husband of Isis and father of Horus.",
    symbols: "Crook and flail, atef crown, mummy wrappings, djed pillar.",
    curiosities: "Murdered and dismembered by Set, then reassembled by Isis; judge of the dead.",
    quote: "Death is not the end, but a transformation.",
    quoteSource: "Egyptian Book of the Dead",
    description:
      "Osiris is the ancient Egyptian god of the dead, underworld, and rebirth. After being murdered and dismembered by his brother Set, he was magically reassembled by his wife Isis. As ruler of the underworld, he judges the souls of the dead and grants eternal life to the worthy.",
  },
  Thoth: {
    name: "Thoth",
    egyptianName: "Ḏḥwtj",
    category: "EGYPTIAN",
    image: "thoth.webp",
    origins: "God of wisdom, writing, and judgment; scribe of the gods and keeper of divine records.",
    symbols: "Ibis, baboon, writing palette, papyrus, scales.",
    curiosities: "Invented writing and mathematics; records the hearts' weights during judgment of the dead.",
    quote: "Knowledge is the gift of the gods to humanity.",
    quoteSource: "Egyptian wisdom literature",
    description:
      "Thoth is the ancient Egyptian god of wisdom, writing, and judgment. Depicted as an ibis-headed man or baboon, he serves as scribe to the gods and keeper of divine knowledge. He invented writing, mathematics, and the sciences, and records the results when hearts are weighed in the afterlife.",
  },
  Hathor: {
    name: "Hathor",
    egyptianName: "Ḥwt-Ḥر",
    category: "EGYPTIAN",
    image: "hathor.webp",
    origins: "Goddess of love, beauty, music, and motherhood; protector of women and children.",
    symbols: "Cow horns with solar disk, sistrum, mirror, cow.",
    curiosities: "Could appear as loving mother or fierce lioness; associated with the Milky Way.",
    quote: "Love and joy are the gifts I bring to mortals.",
    quoteSource: "Egyptian hymns to Hathor",
    description:
      "Hathor is the ancient Egyptian goddess of love, beauty, music, and motherhood. Often depicted with cow horns and a solar disk, she protects women, children, and lovers. Known for her dual nature, she could be both nurturing mother and fierce protector when her children were threatened.",
  },

  // Japanese Deities
  Amaterasu: {
    name: "Amaterasu",
    japaneseName: "天照大神",
    category: "JAPANESE",
    image: "amaterasu.webp",
    origins: "Sun goddess and most important Shinto deity; ruler of the heavens and ancestor of imperial family.",
    symbols: "Sun, mirror, jewels, cherry blossoms.",
    curiosities: "Hid in cave plunging world into darkness; emerged when other gods performed dance.",
    quote: "Let there be light to illuminate all realms.",
    quoteSource: "Shinto creation myths",
    description:
      "Amaterasu is the Japanese sun goddess and the most important deity in Shinto. Born from Izanagi's left eye, she rules the heavens and is considered the ancestor of the Japanese imperial family. Her hiding in a cave after conflict with Susanoo represents the cycle of day and night.",
  },
  Susanoo: {
    name: "Susanoo",
    japaneseName: "須佐之男命",
    category: "JAPANESE",
    image: "susanoo.webp",
    origins: "Storm god and brother of Amaterasu; god of the sea and storms.",
    symbols: "Storm clouds, sword, serpent, lightning.",
    curiosities: "Banished from heaven for causing chaos; slayed the eight-headed dragon Yamata-no-Orochi.",
    quote: "The storm cleanses what the sun cannot reach.",
    quoteSource: "Japanese storm mythology",
    description:
      "Susanoo is the Japanese god of storms and the sea. Brother to Amaterasu, his tempestuous nature often caused conflicts with other gods. Despite his chaotic tendencies, he performed heroic deeds including slaying the great serpent Yamata-no-Orochi and discovering the sacred sword Kusanagi.",
  },
  Tsukuyomi: {
    name: "Tsukuyomi",
    japaneseName: "月読命",
    category: "JAPANESE",
    image: "tsukuyomi.webp",
    origins: "Moon god and brother of Amaterasu and Susanoo; ruler of the night.",
    symbols: "Moon, tides, night sky, silver.",
    curiosities: "Killed the food goddess Uke Mochi, causing Amaterasu to never face him again.",
    quote: "In darkness, I bring the gentle light of reflection.",
    quoteSource: "Japanese lunar traditions",
    description:
      "Tsukuyomi is the Japanese god of the moon and night. Born from Izanagi's right eye, he rules the night sky as his sister Amaterasu rules the day. His estrangement from Amaterasu after killing the food goddess explains why the sun and moon are rarely seen together.",
  },
  Inari: {
    name: "Inari",
    japaneseName: "稲荷",
    category: "JAPANESE",
    image: "inari.webp",
    origins: "Japanese kami of rice, fertility, prosperity, and foxes.",
    symbols: "Fox messengers, rice, torii gates, jewels.",
    curiosities: "Has over 40,000 shrines in Japan; can appear as male or female.",
    quote: "Where rice grows, prosperity follows.",
    quoteSource: "Shinto agricultural prayers",
    description: "Inari is the Japanese kami of rice, fertility, prosperity, and foxes. One of the most popular deities in Japan, Inari is served by fox messengers and has thousands of shrines marked by distinctive red torii gates."
  },
  Raijin: {
    name: "Raijin",
    japaneseName: "雷神",
    category: "JAPANESE",
    image: "raijin.webp",
    origins: "Japanese god of lightning, thunder, and storms.",
    symbols: "Drums, lightning, storm clouds, fierce expression.",
    curiosities: "Often paired with Fujin; can be both destructive and beneficial.",
    quote: "My thunder shakes the heavens and announces the storm's arrival.",
    quoteSource: "Japanese storm mythology",
    description: "Raijin is the Japanese god of lightning, thunder, and storms. Depicted with drums and a fierce expression, he creates thunder by beating his taiko drums. He brings both the destructive power of storms and the life-giving rain."
  },
  Fujin: {
    name: "Fujin",
    japaneseName: "風神",
    category: "JAPANESE",
    image: "fujin.webp",
    origins: "Japanese god of wind and storms; brother of Raijin.",
    symbols: "Wind bag, storm clouds, flowing robes.",
    curiosities: "Often depicted alongside Raijin in art and temples.",
    quote: "I carry the breath of the heavens across the earth.",
    quoteSource: "Shinto wind prayers",
    description: "Fujin is the Japanese god of wind, often depicted carrying a large bag of winds. Brother to Raijin, he controls the winds that bring both gentle breezes and destructive typhoons. Together, they govern Japan's weather."
  },
  Hachiman: {
    name: "Hachiman",
    japaneseName: "八幡神",
    category: "JAPANESE",
    image: "hachiman.webp",
    origins: "Japanese god of war, divine protection, and archery.",
    symbols: "Bow and arrow, dove, samurai armor.",
    curiosities: "Protector of warriors and patron of the Minamoto clan.",
    quote: "The righteous warrior fights not for glory, but for protection of the people.",
    quoteSource: "Samurai codes of honor",
    description: "Hachiman is the Japanese god of war, divine protection, and archery. Originally a local deity, he became patron of warriors and the imperial family. He represents the righteous use of martial power for protection rather than conquest."
  },
  Kannon: {
    name: "Kannon",
    japaneseName: "観音",
    category: "JAPANESE",
    image: "kannon.webp",
    origins: "Japanese Buddhist deity of mercy and compassion; form of Avalokiteshvara.",
    symbols: "Lotus, willow branch, water vessel, multiple arms.",
    curiosities: "Can appear in 33 different forms to help beings in need.",
    quote: "Compassion knows no boundaries; all beings deserve salvation.",
    quoteSource: "Buddhist sutras",
    description: "Kannon is the Japanese Buddhist deity of mercy and compassion. Known for appearing in various forms to help those in need, Kannon embodies infinite compassion and the desire to save all sentient beings from suffering."
  },
  Jizo: {
    name: "Jizo",
    japaneseName: "地蔵",
    category: "JAPANESE",
    image: "jizo.webp",
    origins: "Japanese Buddhist deity who protects children and souls in the underworld.",
    symbols: "Staff with rings, wish-fulfilling jewel, monk's robes.",
    curiosities: "Protects children who die young and helps souls in hell.",
    quote: "No soul is beyond redemption; I will guide all to salvation.",
    quoteSource: "Jizo Buddhist texts",
    description: "Jizo is the Japanese Buddhist deity who protects children, travelers, and souls in the underworld. Often depicted as a monk with a staff and jewel, he is known for his vow to save all beings, especially children and those suffering in hell."
  },
  Tenjin: {
    name: "Tenjin",
    japaneseName: "天神",
    category: "JAPANESE",
    image: "tenjin.webp",
    origins: "Japanese deity of learning, literature, and academic achievement.",
    symbols: "Plum blossoms, scholarly robes, writing implements.",
    curiosities: "Based on historical figure Sugawara no Michizane; patron of students.",
    quote: "Knowledge is the greatest treasure one can possess.",
    quoteSource: "Scholarly traditions",
    description: "Tenjin is the Japanese deity of learning, literature, and academic achievement. Originally the deified spirit of scholar Sugawara no Michizane, he became patron of students and scholars. His shrines are popular before exams."
  },

  // Celtic Deities
  Cernunnos: {
    name: "Cernunnos",
    celticName: "Cernunnos",
    category: "CELTIC",
    image: "cernunnos.webp",
    origins: "Horned god of fertility, animals, life, and the underworld; lord of wild things.",
    symbols: "Antlers, serpent, torc, animals, Celtic cross.",
    curiosities: 'Often called "The Horned God"; associated with the cycle of life, death, and rebirth.',
    quote: "I am the wildness that dwells in the heart of all living things.",
    quoteSource: "Celtic nature traditions",
    description:
      "Cernunnos is the Celtic horned god of fertility, animals, life, and the underworld. Depicted with antlers and surrounded by animals, he represents the wild, untamed aspects of nature and the cycle of life, death, and rebirth. He bridges the world of the living and the dead.",
  },
  Morrigan: {
    name: "Morrigan",
    celticName: "An Mhórrígan",
    category: "CELTIC",
    image: "morrigan.webp",
    origins: "Triple goddess of war, fate, and death; appears as crow or raven on battlefields.",
    symbols: "Crow, raven, cauldron, spear, river.",
    curiosities: "Can appear as three sisters or single entity; prophesies outcomes of battles.",
    quote: "I am the crow that feeds on the battlefield, the fate that cannot be changed.",
    quoteSource: "Irish war poetry",
    description:
      "The Morrigan is the Celtic triple goddess of war, fate, and death. She appears as a crow or raven on battlefields, determining who lives and dies. Known for her prophecies and her role in the Táin Bó Cúailnge, she represents the inexorable nature of fate and the cycle of conflict.",
  },
  Brigid: {
    name: "Brigid",
    celticName: "Brighid",
    category: "CELTIC",
    image: "brigid.webp",
    origins: "Triple goddess of poetry, smithcraft, and healing; patron of druids and craftspeople.",
    symbols: "Fire, forge, well, cross, swan.",
    curiosities: "Became Saint Brigid in Christianity; festival Imbolc celebrates her return.",
    quote: "From my forge comes both word and blade, both healing and creation.",
    quoteSource: "Celtic craft traditions",
    description:
      "Brigid is the Celtic triple goddess of poetry, smithcraft, and healing. Patron of druids, poets, and craftspeople, she represents the creative fire that inspires art and innovation. Her festival, Imbolc, celebrates the return of light and the beginning of spring.",
  },
  Lugh: {
    name: "Lugh",
    celticName: "Lugh",
    category: "CELTIC",
    image: "lugh.webp",
    origins: "God of skill, craft, and excellence; master of all arts and leader of the Tuatha Dé Danann.",
    symbols: "Spear, sling, raven, light, harvest.",
    curiosities: "Festival Lughnasadh celebrates harvest; skilled in every craft and art.",
    quote: "I am skilled in all arts, master of every craft.",
    quoteSource: "Irish mythological cycles",
    description:
      'Lugh is the Celtic god of skill, craft, and excellence. Known as "Samildánach" (skilled in all arts), he leads the Tuatha Dé Danann and represents the highest achievement in all endeavors. The harvest festival Lughnasadh is celebrated in his honor.',
  },
  Manannán: {
    name: "Manannán",
    celticName: "Manannán mac Lir",
    category: "CELTIC",
    image: "manannan.webp",
    origins: "Sea god and guardian of the Otherworld; ferries souls between worlds.",
    symbols: "Boat, mist, crane bag, pigs, sea.",
    curiosities: "Isle of Man named after him; owns boat that sails without wind or oar.",
    quote: "I am the mist between worlds, the tide that brings souls home.",
    quoteSource: "Celtic sea traditions",
    description:
      "Manannán mac Lir is the Celtic god of the sea and guardian of the Otherworld. He ferries souls between the world of the living and the dead, often appearing in mist or fog. The Isle of Man is named after him, and he possesses magical items including a boat that sails without wind.",
  },
  Danu: {
    name: "Danu",
    celticName: "Danu",
    category: "CELTIC",
    image: "danu.webp",
    origins: "Mother goddess of the Tuatha Dé Danann; goddess of wisdom, fertility, and the earth.",
    symbols: "Earth, rivers, sacred wells, cauldron.",
    curiosities: "River Danube named after her; mother of the Irish gods.",
    quote: "I am the earth that nurtures, the wisdom that flows like rivers.",
    quoteSource: "Celtic mother goddess traditions",
    description:
      "Danu is the Celtic mother goddess and matriarch of the Tuatha Dé Danann. As goddess of wisdom, fertility, and the earth, she represents the nurturing aspect of the divine feminine. Rivers, particularly the Danube, are named in her honor, and she is considered the mother of the Irish gods.",
  },
  Aengus: {
    name: "Aengus",
    celticName: "Aengus Óg",
    category: "CELTIC",
    image: "aengus.webp",
    origins: "Celtic god of love, youth, and poetic inspiration.",
    symbols: "Swans, harp, golden hair, four birds around his head.",
    curiosities: "His kisses become birds that inspire love; eternally young.",
    quote: "Love is the music that makes the heart sing.",
    quoteSource: "Irish romantic poetry",
    description: "Aengus Óg is the Celtic god of love, youth, and poetic inspiration. Known for his golden hair and the four birds that circle his head representing his kisses, he brings love and inspiration to mortals and immortals alike."
  },
  Dagda: {
    name: "Dagda",
    celticName: "An Dagda",
    category: "CELTIC",
    image: "dagda.webp",
    origins: "Celtic father god of fertility, agriculture, and protection.",
    symbols: "Magic cauldron, oak club, harp.",
    curiosities: "His cauldron never empties; can kill nine men with one blow of his club.",
    quote: "From my cauldron, none shall go hungry; with my club, none shall harm the innocent.",
    quoteSource: "Irish mythological texts",
    description: "The Dagda is the Celtic father god and protector of the tribe. Owner of a magical cauldron that never empties and a massive club that can kill or heal, he represents abundance, protection, and the power of the good king."
  },
  Epona: {
    name: "Epona",
    celticName: "Epona",
    category: "CELTIC",
    image: "epona.webp",
    origins: "Celtic goddess of horses, fertility, and sovereignty.",
    symbols: "Horse, foal, cornucopia, keys.",
    curiosities: "Only Celtic deity officially adopted into Roman pantheon.",
    quote: "Swift as the wind, strong as the earth, I carry kings to their destiny.",
    quoteSource: "Gaulish horse prayers",
    description: "Epona is the Celtic goddess of horses, fertility, and sovereignty. Revered by both Celts and Romans, she protected horses and their riders. Her association with sovereignty made her important to Celtic kingship rituals."
  },

  // Aztec Deities
  Quetzalcoatl: {
    name: "Quetzalcoatl",
    aztecName: "Quetzalcōātl",
    category: "AZTEC",
    image: "quetzalcoatl.webp",
    origins: "Feathered serpent god of wind, air, and learning; creator deity and cultural hero.",
    symbols: "Feathered serpent, wind, Venus, shells, knowledge.",
    curiosities: "Promised to return from the east; associated with planet Venus.",
    quote: "Knowledge and wisdom are the gifts I bring to humanity.",
    quoteSource: "Aztec educational traditions",
    description:
      "Quetzalcoatl is the Aztec feathered serpent god of wind, air, and learning. As both creator deity and cultural hero, he gave humanity many gifts including knowledge, calendar, and maize. His promise to return from the east played a role in the Spanish conquest of Mexico.",
  },
  Tezcatlipoca: {
    name: "Tezcatlipoca",
    aztecName: "Tezcatlipōca",
    category: "AZTEC",
    image: "tezcatlipoca.webp",
    origins: "Smoking mirror god of night, jaguars, sorcery, and conflict; creator and destroyer.",
    symbols: "Obsidian mirror, jaguar, night sky, smoking foot.",
    curiosities: "Lost his foot to the earth monster; eternal rival of Quetzalcoatl.",
    quote: "I am the mirror that shows both creation and destruction.",
    quoteSource: "Aztec duality philosophy",
    description:
      'Tezcatlipoca is the Aztec god of night, jaguars, sorcery, and conflict. Known as the "Smoking Mirror," he represents the dark aspects of divinity and the necessary balance between creation and destruction. His eternal conflict with Quetzalcoatl drives the cycles of the world.',
  },
  Huitzilopochtli: {
    name: "Huitzilopochtli",
    aztecName: "Huītzilōpōchtli",
    category: "AZTEC",
    image: "huitzilopochtli.webp",
    origins: "God of war, sun, and human sacrifice; patron deity of Tenochtitlan.",
    symbols: "Hummingbird, eagle, fire serpent, shield and spear.",
    curiosities: "Born fully grown and armed; led Aztecs to promised land of Tenochtitlan.",
    quote: "Through sacrifice, the sun rises and the world continues.",
    quoteSource: "Aztec war prayers",
    description:
      "Huitzilopochtli is the Aztec god of war, sun, and human sacrifice. Patron deity of Tenochtitlan, he guided the Aztecs to their promised land and demanded regular sacrifices to ensure the sun's daily journey across the sky. His worship was central to Aztec imperial ideology.",
  },
  Tlaloc: {
    name: "Tlaloc",
    aztecName: "Tlāloc",
    category: "AZTEC",
    image: "tlaloc.webp",
    origins: "God of rain, fertility, and water; ruler of the fourth level of heaven.",
    symbols: "Rain, lightning, mountains, jade, goggle-eyes.",
    curiosities: "Children sacrificed to him for rain; paradise Tlalocan for those who died by water.",
    quote: "I bring the rains that make the earth fertile and green.",
    quoteSource: "Aztec agricultural prayers",
    description:
      "Tlaloc is the Aztec god of rain, fertility, and water. Depicted with goggle-like eyes and fanged mouth, he controls rainfall crucial for agriculture. Those who died by drowning or lightning went to his paradise, Tlalocan, rather than the usual underworld.",
  },
  Xochiquetzal: {
    name: "Xochiquetzal",
    aztecName: "Xōchiquetzal",
    category: "AZTEC",
    image: "xochiquetzal.webp",
    origins: "Goddess of love, beauty, flowers, and sexuality; patron of artists and craftspeople.",
    symbols: "Flowers, butterflies, birds, marigolds, quetzal feathers.",
    curiosities: "Protector of young mothers and lovers; associated with the planet Venus.",
    quote: "I am the flower that blooms in the heart of all who love.",
    quoteSource: "Aztec love poetry",
    description:
      "Xochiquetzal is the Aztec goddess of love, beauty, flowers, and sexuality. Patron of artists, craftspeople, and lovers, she represents the creative and reproductive forces of nature. Her festival featured flower offerings and was associated with the planet Venus.",
  },
  Mictlantecuhtli: {
    name: "Mictlantecuhtli",
    aztecName: "Mictlāntēcuhtli",
    category: "AZTEC",
    image: "mictlantecuhtli.webp",
    origins: "Lord of the dead and ruler of Mictlan, the underworld; god of death and the bones of the dead.",
    symbols: "Skull, bones, owl, spider, darkness.",
    curiosities: "Quetzalcoatl stole bones from him to create new humans; married to Mictlancihuatl.",
    quote: "All paths lead to my realm; I am the final destination.",
    quoteSource: "Aztec death rituals",
    description:
      "Mictlantecuhtli is the Aztec lord of the dead and ruler of Mictlan, the underworld. As god of death and keeper of bones, he governs the souls of those who died natural deaths. His bones were stolen by Quetzalcoatl to create the current race of humans, showing death's role in creating life.",
  },
  Chalchiuhtlicue: {
    name: "Chalchiuhtlicue",
    aztecName: "Chalchiuhtlicue",
    category: "AZTEC",
    image: "chalchiuhtlicue.webp",
    origins: "Aztec goddess of rivers, lakes, and flowing water; wife of Tlaloc.",
    symbols: "Jade skirt, water, river, precious stones.",
    curiosities: "Destroyed the Fourth Sun with a great flood to create the current world.",
    quote: "From my jade waters flows the life of the world.",
    quoteSource: "Aztec creation myths",
    description: "Chalchiuhtlicue is the Aztec goddess of rivers, lakes, and flowing water. Known as 'She of the Jade Skirt,' she is wife to the rain god Tlaloc. She destroyed the Fourth Sun with a great flood, allowing the Fifth Sun to be created."
  },
  Coyolxauhqui: {
    name: "Coyolxauhqui",
    aztecName: "Coyolxauhqui",
    category: "AZTEC",
    image: "coyolxauhqui.webp",
    origins: "Aztec moon goddess; sister of Huitzilopochtli.",
    symbols: "Moon, bells, dismembered body, golden bells.",
    curiosities: "Dismembered by her brother Huitzilopochtli; became the moon.",
    quote: "Even in pieces, I shine in the darkness to guide the lost.",
    quoteSource: "Aztec lunar ceremonies",
    description: "Coyolxauhqui is the Aztec moon goddess, sister to Huitzilopochtli. After leading a rebellion against their mother, she was dismembered by her brother and became the moon. Her story represents the eternal cycle of lunar phases."
  },
  Mixcoatl: {
    name: "Mixcoatl",
    aztecName: "Mixcoatl",
    category: "AZTEC",
    image: "mixcoatl.webp",
    origins: "Aztec god of the hunt, war, and the Milky Way.",
    symbols: "Bow and arrow, stars, hunting gear, red and black body paint.",
    curiosities: "Father of Quetzalcoatl; associated with the Milky Way constellation.",
    quote: "The hunt teaches patience, skill, and respect for all life.",
    quoteSource: "Aztec hunting traditions",
    description: "Mixcoatl is the Aztec god of the hunt, war, and the Milky Way. Father of Quetzalcoatl, he represents the skills needed for survival and the celestial hunt depicted in the night sky. He taught humans the art of hunting."
  },
  Tlazolteotl: {
    name: "Tlazolteotl",
    aztecName: "Tlazolteotl",
    category: "AZTEC",
    image: "tlazolteotl.webp",
    origins: "Aztec goddess of fertility, sexuality, and purification.",
    symbols: "Cotton, weaving, earth, moon phases.",
    curiosities: "Both creates sin and provides purification; patron of midwives.",
    quote: "I am both the transgression and the absolution; sin and redemption are one.",
    quoteSource: "Aztec confession rituals",
    description: "Tlazolteotl is the Aztec goddess of fertility, sexuality, and purification. Known as both the creator of sin and its purifier, she represents the duality of human nature. She protects women in childbirth and governs confession rituals."
  },
};

// Categories data for dynamic category page generation
const categoriesData = [
  {
    id: "greek",
    title: "GREEK MYTHOLOGY",
    description:
      "A rich tapestry of gods, heroes, and mythical creatures, Greek mythology explores the origins of the world, the nature of fate, and the struggles between mortals and the divine. Its timeless stories continue to inspire through tales of love, war, wisdom, and hubris.",
    image: "assets/images/categories/greek.webp",
    color: "#b8860b",
  },
  {
    id: "egyptian",
    title: "EGYPTIAN MYTHOLOGY",
    description:
      "Spanning over three millennia, Egyptian mythology centers around the life-giving Nile River and the eternal cycle of death and rebirth. These beliefs shaped one of history's greatest civilizations with elaborate afterlife concepts and divine kingship.",
    image: "assets/images/categories/egyptian.webp",
    color: "#DAA520",
  },
  {
    id: "norse",
    title: "NORSE MYTHOLOGY",
    description:
      "Originating from Scandinavian and Germanic peoples, Norse mythology presents a complex cosmology centered around nine interconnected worlds. It reflects warrior culture and features the prophesied end of the world in Ragnarök.",
    image: "assets/images/categories/norse.webp",
    color: "#4682b4",
  },
  {
    id: "roman",
    title: "ROMAN MYTHOLOGY",
    description:
      "Evolved from indigenous Italian beliefs and Greek traditions, Roman mythology emphasizes civic duty, state loyalty, and the divine mandate of Roman rule. It features founding legends and gods adapted to reflect Roman values.",
    image: "assets/images/categories/roman.webp",
    color: "#8b0000",
  },
  {
    id: "japanese",
    title: "JAPANESE MYTHOLOGY",
    description:
      "Rooted in Shinto beliefs and influenced by Buddhism, Japanese mythology presents kami spirits, creation myths, and heroic tales that form the foundation of Japanese cultural identity and spiritual practices.",
    image: "assets/images/categories/japanese.webp",
    color: "#DC143C",
  },
  {
    id: "celtic",
    title: "CELTIC MYTHOLOGY",
    description:
      "Encompasses spiritual traditions across Ireland, Scotland, Wales, and ancient Gaul. Features the Otherworld, divine sovereignty, and the thin boundary between mortal and magical realms.",
    image: "assets/images/categories/celtic.webp",
    color: "#228B22",
  },
  {
    id: "aztec",
    title: "AZTEC MYTHOLOGY",
    description:
      "Rich Mesoamerican traditions centered around powerful deities like Quetzalcoatl and Tezcatlipoca. Features complex creation myths, human sacrifice rituals, and the cyclical destruction and rebirth of worlds through cosmic ages.",
    image: "assets/images/categories/aztec.webp",
    color: "#7209b7",
  },
];

// Mythology content data for dynamic page generation
const mythologyData = {
  GREEK: {
    title: "GREEK MYTHOLOGY",
    color: "#b8860b",
    image: "assets/images/categories/greek.webp",
    content: [
      "Greek mythology is one of the most influential mythological traditions in human history. Rooted in the beliefs and oral traditions of ancient Greece, it includes rich tapestry of gods, heroes, creatures, and symbolic tales that helped early Greeks understand the world around them. These myths were passed down through generations and eventually recorded in epic poems, plays and philosophical texts.",
      "At the heart of Greek mythology are the Twelve Olympians, the major gods who lived atop Mount Olympus. Zeus, the ruler of the gods, wielded thunderbolts and maintained order among gods and mortals. His wife, Hera, was the goddess of marriage and family. Other key deities included Poseidon, the god of the sea; Demeter, goddess of the harvest; Apollo, the god of the sun and music; Artemis, goddess of the hunt; Athena, goddess of wisdom and war; and Aphrodite, goddess of love.",
      "The myths are not just about gods; they also explore the lives of mortal and heroic who interacted with the divine. Figures like Perseus, Theseus, Achilles, and Heracles (Hercules) embarked on epic quests and battles that tested their strength, courage, and fate. These stories often taught moral lessons and reflected human struggles, such as pride, loyalty, betrayal, and perseverance.",
      "Greek mythology also included tales of creation and the cosmos, such as the story of Chaos, the void from which the first gods emerged. The Titans, the powerful beings who ruled before the Olympians, were eventually overthrown by Zeus and his siblings in a great war known as the Titanomachy.",
      "Myths like the Trojan War, as told in Homer's Iliad, and the long journey of Odysseus in The Odyssey, are cornerstones of Greek literature and world mythology. Figures like the tales of Prometheus (who gave fire to humans), Pandora (whose curiosity unleashed evil into the world), and Orpheus and Eurydice (a tragic love story), have inspired countless works of art, music, and film.",
      "Greek mythology wasn't just entertainment—it played a central role in religious practice. Temples were built honoring the gods. Rituals and festivals were held in their names, and oracles like the one at Delphi were consulted for divine guidance.",
      'Even today, Greek mythology continues to shape modern language (words like "narcissistic," "titanic," or "echo"), psychology (such as the "Oedipus complex"), and popular culture (like Percy Jackson or Marvel\'s interpretation of mythical figures).',
    ],
  },
  ROMAN: {
    title: "ROMAN MYTHOLOGY",
    color: "#8b0000",
    image: "assets/images/categories/roman.webp",
    content: [
      "Roman mythology evolved from the rich cultural blend of indigenous Italian beliefs, Etruscan traditions, and heavily borrowed Greek mythology. While Romans adopted many Greek gods and stories, they adapted them to reflect Roman values of duty, honor, and state loyalty.",
      "The Roman pantheon featured gods with both Greek origins and uniquely Roman characteristics. Jupiter (Zeus) reigned as king of the gods, while Mars held special significance as both god of war and father of Romulus and Remus, the legendary founders of Rome. Other major deities included Venus (goddess of love), Minerva (wisdom), Diana (hunt), and Neptune (sea).",
      "Roman mythology placed greater emphasis on the founding legends of Rome itself. The story of Aeneas, a Trojan hero who fled to Italy after Troy's fall, became central to Roman identity through Virgil's Aeneid. The tale of Romulus and Remus, twin brothers raised by a wolf who founded Rome, embodied Roman ideals of destiny and divine favor.",
      "Unlike Greek mythology's focus on individual heroism and personal relationships with gods, Roman myths often emphasized civic duty, sacrifice for the state, and the divine mandate of Roman rule. Stories frequently illustrated the importance of pietas (duty to gods, family, and country).",
      "Roman religious practice was highly organized and state-controlled. The pontifex maximus oversaw religious ceremonies, while vestal virgins maintained the sacred flame of Vesta. Festivals like Saturnalia and Lupercalia became central to Roman social life.",
      "The Romans also developed a complex system of household gods (Lares and Penates) and ancestor worship that reflected their strong family values. Mystery religions from the East, such as the cult of Mithras, gained popularity among soldiers and citizens seeking personal salvation.",
      "Roman mythology's influence extended throughout their vast empire, creating a syncretic blend with local traditions that shaped Western civilization's religious and cultural foundations.",
    ],
  },
  NORSE: {
    title: "NORSE MYTHOLOGY",
    color: "#4682b4",
    image: "assets/images/categories/norse.webp",
    content: [
      "Norse mythology, originating from the Scandinavian and Germanic peoples, presents a complex cosmology centered around nine interconnected worlds held together by Yggdrasil, the World Tree. This mythology reflects the harsh realities of Northern European life and the warrior culture of the Vikings.",
      "The Aesir gods, led by Odin the All-Father, ruled from Asgard. Odin, a complex figure seeking wisdom at any cost, sacrificed his eye for knowledge and hung himself from Yggdrasil to discover the runes. Thor, god of thunder, protected both gods and humans with his mighty hammer Mjolnir, while Frigg, Odin's wife, possessed the gift of prophecy.",
      "Central to Norse belief was Ragnarök, the prophesied end of the world where gods and giants would battle in a final conflict. This apocalyptic event would result in the death of many gods, including Odin and Thor, but also the rebirth of the world and surviving gods, representing themes of cyclical destruction and renewal.",
      "The concept of fate (wyrd) permeated Norse mythology. Even the gods were bound by destiny, unable to escape their prophesied doom. This fatalistic worldview reflected the precarious nature of life in medieval Scandinavia, where survival depended on courage, honor, and acceptance of one's fate.",
      "Valhalla, Odin's great hall, welcomed warriors who died bravely in battle (the Einherjar), who would feast and fight until Ragnarök. This belief system elevated the warrior's death in combat and reinforced the martial values essential to Viking society.",
      "Norse mythology featured complex relationships between gods, giants (Jotuns), and other beings. Loki, the trickster god, embodied chaos and change, serving both as helper and eventual destroyer of the gods. His shapeshifting abilities and cunning made him both invaluable and dangerous.",
      "The rich oral tradition of Norse mythology was preserved in medieval Iceland through works like the Prose Edda and Poetic Edda, ensuring these powerful stories continued to influence literature, art, and popular culture into the modern era.",
    ],
  },
  EGYPTIAN: {
    title: "EGYPTIAN MYTHOLOGY",
    color: "#DAA520",
    image: "assets/images/categories/egyptian.webp",
    content: [
      "Egyptian mythology, spanning over three millennia, represents one of the world's longest-lasting religious traditions. Centered around the life-giving Nile River and the eternal cycle of death and rebirth, these beliefs shaped one of history's greatest civilizations.",
      "Ra, the sun god, sailed across the sky in his solar barque each day and through the underworld each night, battling the serpent Apophis to ensure the sun's return. This daily journey symbolized the eternal struggle between order (Ma'at) and chaos, fundamental to Egyptian worldview.",
      "The myth of Osiris, Isis, and Set became central to Egyptian beliefs about death and resurrection. Set's murder and dismemberment of his brother Osiris, followed by Isis's magical restoration of her husband, established the prototype for mummification and the hope for eternal life in the afterworld.",
      "Egyptian mythology was deeply intertwined with kingship. Pharaohs were considered living gods, incarnations of Horus, and upon death became one with Osiris. This divine kingship legitimized royal authority and connected earthly rule with cosmic order.",
      "The complex afterlife journey described in texts like the Book of the Dead reflected sophisticated beliefs about soul, consciousness, and moral judgment. The heart of the deceased was weighed against the feather of Ma'at to determine worthiness for eternal life.",
      "Animal worship played a significant role, with gods often depicted with animal heads or as sacred animals themselves. Cats were associated with Bastet, ibises with Thoth, and crocodiles with Sobek, reflecting the Egyptians' close observation of nature and animal behavior.",
      "Egyptian mythology profoundly influenced neighboring cultures and later Western esoteric traditions. The concept of a dying and resurrecting god, elaborate afterlife beliefs, and the integration of magic with religion left lasting impacts on human spiritual thought.",
    ],
  },
  JAPANESE: {
    title: "JAPANESE MYTHOLOGY",
    color: "#DC143C",
    image: "assets/images/categories/japanese.webp",
    content: [
      "Japanese mythology, rooted in Shinto beliefs and later influenced by Buddhism, presents a rich tapestry of kami (spirits), creation myths, and heroic tales that form the foundation of Japanese cultural identity and spiritual practices.",
      "The creation myth begins with the divine couple Izanagi and Izanami, who stirred the primordial ocean with a jeweled spear to create the Japanese islands. Their subsequent children became the various kami of natural forces, establishing the Shinto belief that divine spirits inhabit all aspects of nature.",
      "Amaterasu, the sun goddess and most important Shinto deity, emerged from Izanagi's left eye and became ruler of the heavens. Her conflict with her brother Susanoo, the storm god, and her subsequent hiding in a cave that plunged the world into darkness, illustrates themes of balance between order and chaos.",
      "The imperial family claims direct descent from Amaterasu through her grandson Ninigi, who descended to earth with the three sacred treasures: a mirror, sword, and jeweled necklace. This divine lineage legitimized imperial rule for over two millennia.",
      "Japanese folklore is rich with supernatural beings: tengu (bird-like creatures), kappa (water spirits), and oni (demons) populate stories that teach moral lessons and explain natural phenomena. These creatures often interact with humans, sometimes helping, sometimes hindering.",
      "The influence of Buddhism introduced concepts of karma, reincarnation, and enlightenment, creating a syncretic religious system where Shinto kami became manifestations of Buddhist deities, and Buddhist temples often housed Shinto shrines.",
      "Modern Japanese culture continues to draw heavily from these mythological traditions, with kami worship at shrines remaining central to Japanese life, and mythological themes pervading anime, manga, literature, and popular culture worldwide.",
    ],
  },
  CELTIC: {
    title: "CELTIC MYTHOLOGY",
    color: "#228B22",
    image: "assets/images/categories/celtic.webp",
    content: [
      "Celtic mythology encompasses the rich spiritual traditions of the Celtic peoples across Ireland, Scotland, Wales, Cornwall, Brittany, and parts of ancient Gaul. These intertwined mythologies share common themes while maintaining distinct regional variations.",
      "The Tuatha Dé Danann, the divine tribe of the goddess Danu, represents the most prominent group of Irish deities. Led by figures like Lugh (god of skill and craft), Brigid (goddess of poetry, smithcraft, and healing), and the Dagda (the good god), they ruled Ireland before retreating to the Otherworld.",
      "Celtic mythology emphasizes the thin boundary between the mortal world and the Otherworld (Tír na nÓg). This magical realm, accessible through sacred sites like stone circles, burial mounds, and certain lakes, was home to the Sidhe (fairy folk) and remained constantly intertwined with human affairs.",
      "The concept of sovereignty was central to Celtic kingship mythology. The land itself was personified as a goddess who would choose worthy kings through ritual marriage or tests. This connection between ruler and land ensured prosperity but also bound the king's fate to the kingdom's wellbeing.",
      "Druids served as priests, judges, teachers, and keepers of oral tradition in Celtic society. They conducted rituals, interpreted omens, and preserved the vast body of myths, laws, and genealogies that held Celtic culture together across tribal boundaries.",
      "Celtic heroes like Cú Chulainn of Ulster and Fionn mac Cumhaill exemplified the warrior ideal while facing supernatural challenges. Their stories often involved geasa (mystical obligations), shape-shifting, and encounters with otherworldly beings that tested their courage and honor.",
      "The arrival of Christianity transformed but didn't eliminate Celtic mythology. Many pagan gods became saints, sacred sites became churches, and festivals like Samhain evolved into Christian celebrations, creating a unique blend that continues to influence Irish, Scottish, and Welsh culture today.",
    ],
  },
  AZTEC: {
    title: "AZTEC MYTHOLOGY",
    color: "#7209b7",
    image: "assets/images/categories/aztec.webp",
    content: [
      "Aztec mythology represents one of the most complex and sophisticated religious systems in Mesoamerican history. Centered in the Valley of Mexico, the Aztec Empire developed intricate beliefs about cosmic cycles, divine sacrifice, and the constant struggle to maintain universal balance.",
      "At the heart of Aztec cosmology stood the concept of the Five Suns - previous worlds that had been created and destroyed by the gods. The current world, the Fifth Sun, was created through divine sacrifice and would eventually meet its end through earthquakes. This cyclical view of creation and destruction permeated all aspects of Aztec religious thought.",
      "Quetzalcoatl, the Feathered Serpent, represented wisdom, fertility, and the wind. As both creator deity and cultural hero, he was said to have given humanity maize, the calendar, and books. His eternal struggle with Tezcatlipoca, the Smoking Mirror god of conflict and change, drove many of the great mythological cycles.",
      "Huitzilopochtli, the god of war and the sun, held special significance as patron deity of the Aztec capital Tenochtitlan. According to myth, he guided the Aztecs to their promised land where they would see an eagle perched on a cactus devouring a serpent - an image that remains central to Mexican identity today.",
      "Human sacrifice played a crucial role in Aztec religion, viewed not as cruelty but as necessary reciprocity with the gods who had sacrificed themselves to create the world. The elaborate rituals at temples like Teotihuacan were designed to ensure the sun's daily journey and maintain cosmic order.",
      "Aztec mythology featured a rich pantheon including Tlaloc the rain god, Xochiquetzal goddess of love and flowers, and Mictlantecuhtli lord of the underworld. Each deity governed specific aspects of life and required proper veneration to maintain their favor and the world's stability.",
      "The arrival of Spanish conquistadors was interpreted through mythological frameworks, with some initially believing Cortés might be the returning Quetzalcoatl. This mythological lens shaped the dramatic encounter between indigenous and European worldviews that would transform the Americas forever."
    ],
  },
};
